### ISSUE TITLE
Event TODO list

### ISSUE THREAD

**Issue by p0t4t0sandwich** [p0t4t0sandwich/TaterLib#20]
- [ ] InventoryOpenEvent
- [ ] InventoryCloseEvent
- [ ] FoodLevelChangeEvent
- [ ] PlayerInteractEvent
- [ ] PlayerInteractEntityEvent
- [ ] PlayerInteractAtEntityEvent
- [ ] EntityShootBowEvent
- [x] EntityDamageEvent (w/ DamageCause) -- need to abstract vanilla DamageCauses, then add a field for modded ones? Not sure how well that'll fit into an enum
- [ ] EntityDamageByEntityEvent (w/ DamageCause)  -- needs entity filter and dedicated event
- [ ] PlayerToggleFlightEvent
- [ ] EntityPotionEffectEvent
- [ ] PlayerGameModeChangeEvent
- [ ] PlayerBucketFillEvent
- [ ] PlayerChangeWorldEvent
- [ ] PlayerRespawnEvent
- [ ] EnittyMountEvent
- [ ] EntityTargetLivingEntityEvent
- [ ] PlayerToggleSneakEvent
- [ ] PlayerAnimationEvent (main hand / off hand swings)
- [ ] PlayerTeleportEvent
- [ ] EntityTeleportEvent
- [x] PlayerJoinEvent
- [x] PlayerQuitEvent
- [x] EntityDeathEvent
- [ ] PlayerDeathEvent -- needs entity filter and dedicated event
- [ ] EntityPortalEnterEvent
- [ ] EntityRegainHealthEvent
- [ ] TimeSkipEvent
- [ ] WeatherChangeEvent
- [ ] ThunderChangeEvent
- [ ] InventoryClickEvent
- [ ] InventoryDragEvent
- [ ] EntityExplodeEvent
- [ ] PlayerMoveEvent
- [ ] EntityPickupItemEvent
- [ ] PlayerPickupArrowEvent
- [ ] PlayerSwapHandItemsEvent
- [ ] PlayerArmorStandManipulateEvent
